/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_havok_Vision_CloudConnectionLifeCycleSupport */

#ifndef _Included_com_havok_Vision_CloudConnectionLifeCycleSupport
#define _Included_com_havok_Vision_CloudConnectionLifeCycleSupport
#ifdef __cplusplus
extern "C" {
#endif
#undef com_havok_Vision_CloudConnectionLifeCycleSupport_MODE_PRIVATE
#define com_havok_Vision_CloudConnectionLifeCycleSupport_MODE_PRIVATE 0L
#undef com_havok_Vision_CloudConnectionLifeCycleSupport_MODE_WORLD_READABLE
#define com_havok_Vision_CloudConnectionLifeCycleSupport_MODE_WORLD_READABLE 1L
#undef com_havok_Vision_CloudConnectionLifeCycleSupport_MODE_WORLD_WRITEABLE
#define com_havok_Vision_CloudConnectionLifeCycleSupport_MODE_WORLD_WRITEABLE 2L
#undef com_havok_Vision_CloudConnectionLifeCycleSupport_MODE_APPEND
#define com_havok_Vision_CloudConnectionLifeCycleSupport_MODE_APPEND 32768L
#undef com_havok_Vision_CloudConnectionLifeCycleSupport_BIND_AUTO_CREATE
#define com_havok_Vision_CloudConnectionLifeCycleSupport_BIND_AUTO_CREATE 1L
#undef com_havok_Vision_CloudConnectionLifeCycleSupport_BIND_DEBUG_UNBIND
#define com_havok_Vision_CloudConnectionLifeCycleSupport_BIND_DEBUG_UNBIND 2L
#undef com_havok_Vision_CloudConnectionLifeCycleSupport_BIND_NOT_FOREGROUND
#define com_havok_Vision_CloudConnectionLifeCycleSupport_BIND_NOT_FOREGROUND 4L
#undef com_havok_Vision_CloudConnectionLifeCycleSupport_CONTEXT_INCLUDE_CODE
#define com_havok_Vision_CloudConnectionLifeCycleSupport_CONTEXT_INCLUDE_CODE 1L
#undef com_havok_Vision_CloudConnectionLifeCycleSupport_CONTEXT_IGNORE_SECURITY
#define com_havok_Vision_CloudConnectionLifeCycleSupport_CONTEXT_IGNORE_SECURITY 2L
#undef com_havok_Vision_CloudConnectionLifeCycleSupport_CONTEXT_RESTRICTED
#define com_havok_Vision_CloudConnectionLifeCycleSupport_CONTEXT_RESTRICTED 4L
#undef com_havok_Vision_CloudConnectionLifeCycleSupport_RESULT_CANCELED
#define com_havok_Vision_CloudConnectionLifeCycleSupport_RESULT_CANCELED 0L
#undef com_havok_Vision_CloudConnectionLifeCycleSupport_RESULT_OK
#define com_havok_Vision_CloudConnectionLifeCycleSupport_RESULT_OK -1L
#undef com_havok_Vision_CloudConnectionLifeCycleSupport_RESULT_FIRST_USER
#define com_havok_Vision_CloudConnectionLifeCycleSupport_RESULT_FIRST_USER 1L
#undef com_havok_Vision_CloudConnectionLifeCycleSupport_DEFAULT_KEYS_DISABLE
#define com_havok_Vision_CloudConnectionLifeCycleSupport_DEFAULT_KEYS_DISABLE 0L
#undef com_havok_Vision_CloudConnectionLifeCycleSupport_DEFAULT_KEYS_DIALER
#define com_havok_Vision_CloudConnectionLifeCycleSupport_DEFAULT_KEYS_DIALER 1L
#undef com_havok_Vision_CloudConnectionLifeCycleSupport_DEFAULT_KEYS_SHORTCUT
#define com_havok_Vision_CloudConnectionLifeCycleSupport_DEFAULT_KEYS_SHORTCUT 2L
#undef com_havok_Vision_CloudConnectionLifeCycleSupport_DEFAULT_KEYS_SEARCH_LOCAL
#define com_havok_Vision_CloudConnectionLifeCycleSupport_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_havok_Vision_CloudConnectionLifeCycleSupport_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_havok_Vision_CloudConnectionLifeCycleSupport_DEFAULT_KEYS_SEARCH_GLOBAL 4L
/*
 * Class:     com_havok_Vision_CloudConnectionLifeCycleSupport
 * Method:    nativeOnActivityCreated
 * Signature: (Landroid/app/Activity;Landroid/os/Bundle;)V
 */
JNIEXPORT void JNICALL Java_com_havok_Vision_CloudConnectionLifeCycleSupport_nativeOnActivityCreated
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_havok_Vision_CloudConnectionLifeCycleSupport
 * Method:    nativeOnActivityDestroyed
 * Signature: (Landroid/app/Activity;)V
 */
JNIEXPORT void JNICALL Java_com_havok_Vision_CloudConnectionLifeCycleSupport_nativeOnActivityDestroyed
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_havok_Vision_CloudConnectionLifeCycleSupport
 * Method:    nativeOnActivityPaused
 * Signature: (Landroid/app/Activity;)V
 */
JNIEXPORT void JNICALL Java_com_havok_Vision_CloudConnectionLifeCycleSupport_nativeOnActivityPaused
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_havok_Vision_CloudConnectionLifeCycleSupport
 * Method:    nativeOnActivityResumed
 * Signature: (Landroid/app/Activity;)V
 */
JNIEXPORT void JNICALL Java_com_havok_Vision_CloudConnectionLifeCycleSupport_nativeOnActivityResumed
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_havok_Vision_CloudConnectionLifeCycleSupport
 * Method:    nativeOnActivitySaveInstanceState
 * Signature: (Landroid/app/Activity;Landroid/os/Bundle;)V
 */
JNIEXPORT void JNICALL Java_com_havok_Vision_CloudConnectionLifeCycleSupport_nativeOnActivitySaveInstanceState
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_havok_Vision_CloudConnectionLifeCycleSupport
 * Method:    nativeOnActivityStarted
 * Signature: (Landroid/app/Activity;)V
 */
JNIEXPORT void JNICALL Java_com_havok_Vision_CloudConnectionLifeCycleSupport_nativeOnActivityStarted
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_havok_Vision_CloudConnectionLifeCycleSupport
 * Method:    nativeOnActivityStopped
 * Signature: (Landroid/app/Activity;)V
 */
JNIEXPORT void JNICALL Java_com_havok_Vision_CloudConnectionLifeCycleSupport_nativeOnActivityStopped
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
